services:


    app:
        build:
            args:
                user: harry
                uid: 1000
            context: ./
            #dockerfile: Dockerfile.dev
            dockerfile: Dockerfile.swooledev
        working_dir: /var/www/
        restart: unless-stopped
        ports:
            - "8000:8000"
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        links:
            - db
        depends_on:
            - db
        volumes:
            - ./:/var/www
        networks:
            - harrynet


    # DATABASE SERVER
    db: # nama ini terserah kita
        container_name: db
        image: mysql:8.0 # versi mysql
        restart: unless-stopped
        ports:
            - "3344:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - harrynet

    
    # NGINX SERVER
    nginx:
        image: nginx:alpine
        container_name: nginx_tokobangunan
        restart: unless-stopped
        tty: true
        links:
            - app
        depends_on:
            - db
            - app
        ports:
            - "8182:80"
            - "8500:8000"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - harrynet



    
networks:
    harrynet:
        driver: bridge


volumes:
    db_data:
        driver: local
