FROM php:8.3-fpm

# Arguments defined in docker-compose.yml
ARG user
ARG uid

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    libzip-dev \
    libss

# Install PHP extensions

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*



# Get latest Composer & install composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer





# TODO not use node in producation
# RUN apk add --no-cache nodejs npm git

# COPY docker-compose/php/supervisord/supervisord.conf /etc/

# Create system user to run Composer and Artisan Commands
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

COPY . /var/www
COPY --chown=www:www . /var/www

USER www

EXPOSE 8000

CMD ["php-fpm"]